name: Daily AI Cost Notification

on:
  push:
    branches: [main]
  schedule:
    # Run at 8:00 AM JST (23:00 UTC)
    - cron: "0 23 * * *"
  workflow_dispatch: # Allow manual triggering

jobs:
  send-notification:
    runs-on: ubuntu-latest
    environment: default
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run notification script
        run: node index.js
        env:
          ANTHROPIC_ORGANIZATION_ID: ${{ secrets.ANTHROPIC_ORGANIZATION_ID }}
          OPENAI_ADMIN_KEY: ${{ secrets.OPENAI_ADMIN_KEY }}
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
